export interface Cuenta {
    "codCli": string,
    "nomCli": string,
    "nitCli": string,
    "codCiu": string,
    "codDep": string,
    "codPai": string,
    "di2Cli": string,
    "te1Cli": string,
    "tipCli": number,
    "fecIng": string,
    "eMail": string,
    "tipIde": string,
    "ap1Cli": string,
    "nom1Cli": string,
    "tipPer": number,
    "estCli": string,
    "codCliExtr": string,
    "pagWeb": string
}
